[package]
name = "galloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = { version = "0.9.4", optional = true }
static_assertions = "1.1.0"

[dev-dependencies]
rand =  { version = "0.8.5", features = ["small_rng"] }
galloc = { path = ".", features = ["spin", "allocator"] }
linked_list_allocator = "0.10.3"
simple-chunk-allocator = "0.1.5"
strum = "0.24.1"
strum_macros = "0.24.1"
arrayvec = "0.7.2"
const-random = "0.1.13"

[features]
default = ["spin"]
allocator = []
